[package]
name = "http_client-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls = "0.20.0"
rustls-pemfile = "1.0.0"
webpki = "0.21.0"
webpki-roots = "0.19"
chrono = "0.4"
